/* UI kit Keys interactions. Emits key:change; consumers own routing and side effects. */
(() => {
 let scope=null,controller=null,resizeObserver=null,dialog=null,returnFocus=null,toastTimer=null;
 const T=window.KeyTemplates;
 const uploadURLs=new Set();let pointerStart=null;
 const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
 const emit=(el,component,type,value)=>el.dispatchEvent(new CustomEvent('key:change',{bubbles:true,detail:{component,type,value}}));
 const animate=(el,frames,options)=>{if(!reduced())return el.animate(frames,options);};
 function toast(message){let el=document.getElementById('key-toast');if(!el){el=document.createElement('div');el.id='key-toast';el.className='k-toast key-ui';el.setAttribute('role','status');el.setAttribute('aria-live','polite');document.body.append(el);}el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3500);}
 function measureTabs(el){const active=el.querySelector('[role=tab][aria-selected=true]');if(!active)return;el.style.setProperty('--tab-x',active.offsetLeft+'px');el.style.setProperty('--tab-width',active.offsetWidth+'px');}
 function selectTab(button){const list=button.closest('[role=tablist]');list.querySelectorAll('[role=tab]').forEach(b=>{const on=b===button;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;const panel=document.getElementById(b.getAttribute('aria-controls'));if(panel)panel.hidden=!on;});measureTabs(list);emit(list,'tabs','select',button.id);}
 function closeSheet(){if(dialog?.open)dialog.close();}
 function sheetBody(id){switch(id){
 case 'filters':return `<div class="k-stack"><h2 class="k-title">Фильтры</h2>${T.demos.chips()}${T.demos.checkbox()}${T.demos.switch()}${T.button('Показать отели','','data-close-sheet')}</div>`;
 case 'guests':return `<div class="k-stack"><h2 class="k-title">Гости</h2>${T.demos.stepper()}${T.demos.switch()}${T.button('Готово','','data-close-sheet')}</div>`;
 case 'photos':return `<div class="k-stack"><h2 class="k-title">Добавить фотографии</h2>${T.upload('sheet-photos')}${T.button('Сохранить','','data-close-sheet')}</div>`;
 case 'service':return `<div class="k-stack"><h2 class="k-title">Ранний заезд</h2>${T.demos.select()}${T.button('Добавить услугу','','data-toast="Услуга добавлена" data-close-sheet')}</div>`;
 case 'door':return `<div class="k-stack"><h2 class="k-title">Открыть дверь</h2><p>Номер 412 · 4 этаж</p><p class="k-muted">Подойдите к двери номера</p>${T.button(T.icon('key')+' Открыть','','data-door-open')}<p role="status" data-door-status></p></div>`;
 case 'taxi':return `<div class="k-stack"><span class="k-status k-status--warning">Внешнее приложение</span><h2 class="k-title">Яндекс Go</h2>${T.rows([['Откуда','Ваше местоположение'],['Куда','Maidens Hotel · Москва']])}<p class="k-caption k-muted">В продукте открывается deep link внешнего приложения. Здесь показан только переход.</p></div>`;
 case 'payment':return `<div class="k-stack"><h2 class="k-title">Оплата</h2><p>Пример UI-состояния. Платёжные данные и реальные операции не обрабатываются.</p>${T.button('Показать успешное состояние','','data-toast="Оплата подтверждена — пример состояния" data-close-sheet')}</div>`;
 case 'guest':return `<div class="k-stack"><h2 class="k-title">Данные гостя</h2><label class="k-field">Имя<input class="k-input" autocomplete="given-name"></label><label class="k-field">Фамилия<input class="k-input" autocomplete="family-name"></label>${T.button('Сохранить','','data-close-sheet')}</div>`;
 case 'checkin':return `<div class="k-stack"><h2 class="k-title">Онлайн-регистрация · 2 / 2</h2><p>Проверьте данные гостей перед отправкой.</p>${T.button('Завершить регистрацию','','data-toast="Онлайн-регистрация пройдена" data-close-sheet')}</div>`;
 case 'settings':return `<div class="k-stack"><h2 class="k-title">Настройки уведомлений</h2>${T.demos.switch()}${T.button('Сохранить','','data-close-sheet')}</div>`;
 default:{const map={hotel:'hotel-card',rooms:'room-card',documents:'document-picker',details:'booking-documents',bill:'bill',share:'share',notifications:'notifications',feedback:'feedback',profile:'profile'};return (T.demos[map[id]]||T.demos.card)();}}
 }
 function openSheet(id,opener){if(!dialog){dialog=document.createElement('dialog');dialog.className='k-sheet key-ui';dialog.setAttribute('aria-label','Подробности');dialog.addEventListener('close',()=>{returnFocus?.focus({preventScroll:true});});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientY<r.top||e.clientX<r.left||e.clientX>r.right)closeSheet();}});document.body.append(dialog);if(scope!==document){dialog.addEventListener('click',click);dialog.addEventListener('keydown',keydown);dialog.addEventListener('change',change);dialog.addEventListener('submit',submit);}}if(!dialog.open)returnFocus=opener||document.activeElement;dialog.innerHTML=`<div class="k-row k-between" style="margin-bottom:12px"><span class="k-caption k-muted">UI kit Keys · пример</span><button class="k-icon-button k-icon-button--plain" aria-label="Закрыть" data-close-sheet>${T.icon('close')}</button></div>${sheetBody(id)}`;dialog.setAttribute('aria-label',dialog.querySelector('h2,h3')?.textContent||'Подробности');if(!dialog.open)dialog.showModal();wireGeometry(dialog);}
 async function copy(value){try{await navigator.clipboard.writeText(value);toast('Скопировано');}catch{toast('Копирование недоступно в этом браузере');}}
 function click(e){const b=e.target.closest('button,a,[data-open-sheet]');if(!b||b.disabled)return;
  if(b.matches('[role=tab]'))selectTab(b);
  if(b.hasAttribute('data-nav')){const nav=b.closest('.k-nav');nav.style.setProperty('--nav-index',b.dataset.nav);nav.querySelectorAll('button').forEach(t=>t===b?t.setAttribute('aria-current','page'):t.removeAttribute('aria-current'));animate(b.querySelector('svg'),[{transform:'translateY(0) scale(1)'},{transform:'translateY(-2px) scale(1.14)',offset:.3},{transform:'translateY(0) scale(1)'}],{duration:420,easing:'cubic-bezier(.34,1.56,.64,1)'});emit(nav,'bottom-nav','navigate',['trips','search','chats','benefits'][Number(b.dataset.nav)]);}
  if(b.hasAttribute('data-chip')||b.hasAttribute('data-save')){const on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(on));emit(b,b.hasAttribute('data-save')?'favorite':'chip','toggle',on);}
  if(b.hasAttribute('data-step')){const stepper=b.closest('.k-stepper'),o=stepper.querySelector('output'),v=Math.max(+stepper.dataset.min,Math.min(+stepper.dataset.max,+o.value+(+b.dataset.step)));o.value=String(v);stepper.querySelector('[data-step="-1"]').disabled=v===+stepper.dataset.min;stepper.querySelector('[data-step="1"]').disabled=v===+stepper.dataset.max;emit(stepper,'stepper','change',v);}
  if(b.hasAttribute('data-rate')){const group=b.closest('.k-rating'),v=+b.dataset.rate;group.dataset.value=v;group.querySelectorAll('button').forEach(t=>{t.dataset.on=String(+t.dataset.rate<=v);t.setAttribute('aria-pressed',String(+t.dataset.rate===v));});group.nextElementSibling.textContent=`Ваша оценка: ${v} из 5`;const flow=group.closest('[data-feedback]');if(flow)flow.querySelector('[data-feedback-next]').disabled=false;emit(group,'rating','rate',v);}
  if(b.matches('[data-prev],[data-next]')){const g=b.closest('.k-gallery'),images=JSON.parse(g.dataset.images),i=((+g.dataset.index)+(b.hasAttribute('data-next')?1:-1)+images.length)%images.length;g.dataset.index=i;g.querySelector('img').src='assets/'+images[i];g.querySelector('img').alt=`Фото ${i+1} из ${images.length}`;g.querySelector('.k-counter').textContent=`${i+1} / ${images.length}`;emit(g,'gallery','change',i);}
  if(b.hasAttribute('data-map-toggle')){const m=b.closest('.k-map'),on=m.dataset.expanded!=='true';m.dataset.expanded=String(on);b.setAttribute('aria-expanded',String(on));b.setAttribute('aria-label',on?'Свернуть карту':'Развернуть карту');emit(m,'map','expand',on);}
  if(b.hasAttribute('data-service')){const added=b.dataset.serviceState==='added';if(added){openSheet('service',b);dialog.innerHTML=`<div class="k-sheet-header"><h2 class="k-title">${T.esc(b.dataset.service)}</h2><button class="k-icon-button" data-close-sheet aria-label="Закрыть">${T.icon('close')}</button></div><p class="k-muted" style="margin-bottom:16px">Услуга добавлена за доплату</p>${T.button('Убрать услугу','secondary','data-remove-service')}`;dialog.querySelector('[data-remove-service]').onclick=()=>{b.dataset.serviceState='available';b.querySelector('[data-service-copy]').textContent='Не включён · можно добавить';b.querySelector('[data-service-copy]').classList.remove('k-positive');b.querySelector('.k-service-action').textContent='Добавить';closeSheet();toast('Услуга удалена');emit(b,'service','remove',b.dataset.service);};}else{b.dataset.serviceState='added';b.querySelector('[data-service-copy]').textContent='Добавлен за доплату';b.querySelector('[data-service-copy]').classList.add('k-positive');b.querySelector('.k-service-action').textContent='Изменить';toast('Услуга добавлена');emit(b,'service','add',b.dataset.service);}}
  if(b.hasAttribute('data-reveal')){const p=b.closest('.k-card').querySelector('[data-password]'),hidden=p.textContent.startsWith('•');p.textContent=hidden?'Welcome2026':'••••••••';b.textContent=hidden?'Скрыть':'Показать';}
  if(b.hasAttribute('data-open-sheet')){e.preventDefault();openSheet(b.dataset.openSheet,b);}
  if(b.hasAttribute('data-close-sheet'))closeSheet();
  if(b.hasAttribute('data-toast'))toast(b.dataset.toast);
  if(b.hasAttribute('data-copy'))copy(b.dataset.copy);
  if(b.hasAttribute('data-download-example'))toast('Событие download: подключите генерацию PDF в приложении');
  if(b.hasAttribute('data-door-open')){const status=b.parentElement.querySelector('[data-door-status]');b.disabled=true;status.textContent='Подключаемся…';setTimeout(()=>{status.textContent='Дверь открыта';b.disabled=false;emit(b,'door','success',412);},1000);}
  if(b.matches('[data-feedback-next],[data-feedback-back],[data-feedback-submit]')){const flow=b.closest('[data-feedback]'),step=b.hasAttribute('data-feedback-next')?'2':b.hasAttribute('data-feedback-back')?'1':'3';flow.querySelectorAll('[data-feedback-step]').forEach(el=>el.hidden=el.dataset.feedbackStep!==step);if(step==='3')flow.querySelector('[data-tips]').hidden=flow.querySelector('.k-rating').dataset.value!=='5';emit(flow,'feedback','step',step);}
  if(b.closest('[data-calendar]')){const cal=b.closest('[data-calendar]'),day=+b.textContent;let start=Number(cal.dataset.start),end=Number(cal.dataset.end);if(!start||end){start=day;end=0;}else{end=day;if(end<start)[start,end]=[end,start];}cal.dataset.start=start;cal.dataset.end=end;cal.querySelectorAll('button').forEach(el=>{const n=+el.textContent;el.setAttribute('aria-pressed',String(n===start||n===end));el.classList.toggle('k-in-range',!!end&&n>start&&n<end);});cal.nextElementSibling.textContent=end?`${start}–${end} сентября · ${end-start} ночей`:`Заезд ${start} сентября · выберите выезд`;emit(cal,'calendar','range',{start,end});}
 }
 function keydown(e){if(e.target.matches('[role=tab]')&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const all=[...e.target.closest('[role=tablist]').querySelectorAll('[role=tab]:not(:disabled)')];let index=all.indexOf(e.target);index=e.key==='Home'?0:e.key==='End'?all.length-1:(index+(e.key==='ArrowRight'?1:-1)+all.length)%all.length;all[index].focus();selectTab(all[index]);}}
 function change(e){if(e.target.matches('[data-upload]')){const input=e.target,list=input.closest('.k-upload').nextElementSibling;list.replaceChildren();for(const file of input.files){const item=document.createElement('span');item.className='k-upload-item';if(file.type.startsWith('image/')){const image=document.createElement('img');image.src=URL.createObjectURL(file);image.alt=file.name;uploadURLs.add(image.src);item.append(image);}const name=document.createElement('span');name.textContent=file.name;item.append(name);const remove=document.createElement('button');remove.type='button';remove.className='k-icon-button k-icon-button--plain';remove.setAttribute('aria-label','Удалить '+file.name);remove.innerHTML=T.icon('close');remove.onclick=()=>{const src=item.querySelector('img')?.src;if(src){URL.revokeObjectURL(src);uploadURLs.delete(src);}item.remove();emit(input,'upload','remove',file.name);};item.append(remove);list.append(item);}emit(input,'upload','select',[...input.files].map(f=>({name:f.name,size:f.size,type:f.type})));}else if(e.target.matches('input,select,textarea'))emit(e.target,'field','change',e.target.type==='checkbox'?e.target.checked:e.target.value);}
 function submit(e){if(e.target.matches('[data-example-form]')){e.preventDefault();toast('Обращение отправлено — пример состояния');emit(e.target,'problem','submit',{});}if(e.target.matches('[data-chat-form]')){e.preventDefault();const input=e.target.querySelector('input'),text=input.value.trim();if(!text)return;const bubble=document.createElement('div');bubble.className='k-chat-bubble k-chat-bubble--out';bubble.textContent=text;e.target.before(bubble);input.value='';emit(e.target,'chat','send',text);}}
 function wireGeometry(root){root.querySelectorAll('.k-tabs').forEach(el=>{measureTabs(el);resizeObserver?.observe(el);});}
 function mount(root=document){if(scope)return wireGeometry(root);scope=root;controller=new AbortController();const options={signal:controller.signal};root.addEventListener('click',click,options);root.addEventListener('keydown',keydown,options);root.addEventListener('change',change,options);root.addEventListener('submit',submit,options);root.addEventListener('pointerdown',e=>{const el=e.target.closest('.k-gallery,.k-map');if(el&&!e.target.closest('button'))pointerStart={el,x:e.clientX,y:e.clientY};},options);root.addEventListener('pointerup',e=>{if(!pointerStart)return;const {el,x,y}=pointerStart;pointerStart=null;const dx=e.clientX-x,dy=e.clientY-y;if(el.matches('.k-gallery')&&Math.abs(dx)>40&&Math.abs(dx)>Math.abs(dy))el.querySelector(dx<0?'[data-next]':'[data-prev]')?.click();if(el.matches('.k-map')&&el.dataset.expanded==='true'&&dy< -45&&Math.abs(dy)>Math.abs(dx))el.querySelector('[data-map-toggle]')?.click();},options);root.addEventListener('pointercancel',()=>pointerStart=null,options);resizeObserver=new ResizeObserver(entries=>entries.forEach(e=>measureTabs(e.target)));wireGeometry(root);document.fonts?.ready.then(()=>scope&&wireGeometry(root));}
 function destroy(){controller?.abort();resizeObserver?.disconnect();closeSheet();dialog?.remove();dialog=null;scope=null;clearTimeout(toastTimer);for(const url of uploadURLs)URL.revokeObjectURL(url);uploadURLs.clear();document.getElementById('key-toast')?.remove();}
 window.KeyUI={mount,toast,openSheet,closeSheet,destroy};
})();
