/* Copyable compositions; no framework and no application backend dependency. */
(() => {
 const icons=window.KEY_DATA.icons;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const icon=(name,small=false)=>`<svg class="k-icon${small?' k-icon--small':''}" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.help}</svg>`;
 const button=(label,variant='',attrs='')=>`<button type="button" class="k-button ${variant?`k-button--${variant}`:''}" ${attrs}>${label}</button>`;
 const status=(label,tone='',check=false)=>`<span class="k-status ${tone?`k-status--${tone}`:''}">${check?icon('check',true):''}${label}</span>`;
 const action=(label='Подробнее')=>`<button class="k-link k-footer" type="button" data-toast="Открыт пример действия"><span>${label}</span>${icon('chevron',true)}</button>`;
 const field=(label,value='',attrs='')=>`<label class="k-field"><span>${label}</span><input class="k-input" value="${esc(value)}" ${attrs}></label>`;
 const tabs=(id,labels=['Список','Карта'],variant='')=>`<div class="k-tabs ${variant?'k-tabs--line':''}" role="tablist" aria-label="${id}">${labels.map((l,i)=>`<button role="tab" id="${id}-tab-${i}" aria-controls="${id}-panel-${i}" aria-selected="${i===0}" tabindex="${i===0?0:-1}">${l}</button>`).join('')}</div>${labels.map((l,i)=>`<div id="${id}-panel-${i}" role="tabpanel" aria-labelledby="${id}-tab-${i}" tabindex="0" ${i?'hidden':''} class="k-caption k-muted">${l}: содержимое выбранной вкладки</div>`).join('')}`;
 const gallery=(photos=['hotel.jpg','restaurant.webp','breakfast.png'])=>`<div class="k-gallery" data-images='${JSON.stringify(photos)}' data-index="0"><img draggable="false" src="assets/${photos[0]}" alt="${photos[0]==='hotel.jpg'?'Интерьер отеля':'Блюда и ресторан отеля'}" loading="lazy"><button class="k-icon-button" data-prev aria-label="Предыдущее фото">${icon('back')}</button><button class="k-icon-button" data-next aria-label="Следующее фото">${icon('arrow')}</button><span class="k-counter" aria-live="polite">1 / ${photos.length}</span></div>`;
 const service=(name,ic,sub,act='Добавить',tone='')=>`<button type="button" class="k-service-row" data-service="${name}" data-service-state="${act==='Изменить'?'added':'available'}"><span class="k-icon-slot">${icon(ic)}</span><span><span class="k-label">${name}</span><span class="k-caption ${tone==='positive'?'k-positive':'k-muted'}" data-service-copy>${sub}</span></span><span class="k-service-action">${act}</span></button>`;
 const rows=(list)=>`<dl class="k-data">${list.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')}</dl>`;
 const hotel=()=>`<article class="k-card k-hotel">${gallery().replace('</div>',`<button class="k-icon-button k-save" data-save aria-pressed="false" aria-label="Сохранить отель">${icon('heart')}</button></div>`)}<a class="k-hotel-body" href="index.html#hotel-details"><div><h3 class="k-section">Maidens Hotel</h3><p class="k-caption k-muted">Москва · 3 км до центра</p></div><div class="k-hotel-price"><strong>28 980 ₽</strong><div><del>31 500 ₽</del> <span class="k-discount">−8%</span></div></div><div class="k-row"><span class="k-score">9,4</span><span class="k-caption k-muted">128 отзывов</span></div></a></article>`;
 const hero=(mode)=>`<article class="k-card k-card--flush"><div class="k-hero-strip">${mode==='before'?`<span class="k-row">${icon('heart')}<span class="k-label">Ждём вас в отеле</span></span>`:`<span class="k-label">Maidens Hotel</span>${status(mode==='after'?'Поездка завершена':'Проживание')}`}</div>${mode==='before'||mode==='after'?'<img class="k-hero-photo" src="assets/hotel.jpg" alt="Maidens Hotel" loading="lazy">':''}<div class="k-hero-body">${mode==='before'?`<div class="k-row"><span class="k-metric">8</span><span>дней до заезда</span></div><h3 class="k-section">Maidens Hotel <span class="k-caption">· Москва</span></h3><div class="k-dates"><div class="k-date-row"><span>12 сентября</span><span class="k-caption">с 14:00</span></div><div class="k-date-row"><span>19 сентября</span><span class="k-caption">до 12:00</span></div></div><div class="k-row k-between"><span class="k-caption">7 ночей · 2 взрослых</span><span class="k-caption">Стандарт</span></div><hr class="k-rule"><div class="k-row k-between"><span class="k-section">44 800 ₽</span>${status('Оплачено', '',true)}</div>`:mode==='stay'?`<div class="k-row k-between"><div><p class="k-caption k-muted">Ваш номер · 4 этаж</p><p class="k-balance">412</p></div><div><p class="k-label">2-й день из 8</p><p class="k-caption k-muted">Выезд 19 сентября, 12:00</p></div></div><div class="k-progress"><span></span></div>${button(icon('key')+' Открыть дверь','secondary','data-open-sheet="door"')}`:`<h3 class="k-section">Maidens Hotel</h3><p class="k-caption k-muted">Москва</p><div class="k-row k-between"><span>12–19 сентября</span><span>7 ночей</span></div>${button('Детали проживания','secondary','data-open-sheet="details"')}`}</div></article>`;
 const rating=id=>`<div class="k-rating" role="group" aria-label="Оценка проживания" data-rating="${id}">${[1,2,3,4,5].map(n=>`<button type="button" data-rate="${n}" aria-label="${n} из 5" aria-pressed="false">${icon('star')}</button>`).join('')}</div><p class="k-caption k-muted" data-rating-label>Выберите оценку</p>`;
 const upload=id=>`<label class="k-upload">${icon('camera')}<span>Прикрепить фото</span><input class="k-sr" type="file" accept="image/*" multiple data-upload="${id}"></label><div class="k-file-list" data-files="${id}" aria-live="polite"></div>`;
 const map=()=>`<div class="k-map" data-expanded="false" aria-label="Иллюстрация карты с отелями"><svg viewBox="0 0 375 300" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><rect width="375" height="300" fill="#eef1e8"/><path d="M-20 235 Q120 100 390 275" fill="none" stroke="#c6dfeb" stroke-width="28"/><path d="M-30 70L430 185M60 -30L250 360M-40 195L400 65M285 -30L80 350" stroke="#fff" stroke-width="12"/><path d="M10 70L115 20L150 70L50 115M290 240L340 180L385 205L370 300" fill="#dce8ce"/></svg><button class="k-map-marker" style="left:20%;top:30%" data-open-sheet="hotel">28 980 ₽</button><button class="k-map-marker" style="left:55%;top:60%" data-open-sheet="hotel">24 400 ₽</button><button class="k-icon-button" data-map-toggle aria-label="Развернуть карту" aria-expanded="false">${icon('map')}</button></div>`;
 const referral=()=>`<article class="k-card k-referral k-stack"><div class="k-row k-between"><h3 class="k-section">Путешествуйте<br>с друзьями</h3><span class="k-icon-slot">${icon('gift')}</span></div><p class="k-muted">Друг установит приложение —<br>вам баллы на новую поездку.</p>${button(icon('share')+' Поделиться ссылкой','secondary','data-open-sheet="share"')}</article>`;
 const demos={
 'button':()=>`<div class="k-stack">${button('Найти отель')}${button('Изменить бронь','secondary')}${button('Сохранить','quiet')}${button('Удалить','danger')}<div class="k-grid">${button('Недоступно','','disabled')}${button('<span class="k-spinner" aria-hidden="true"></span> Сохраняем','','disabled aria-busy="true"')}</div></div>`,
 'link':()=>`<div class="k-card"><p class="k-section">Места рядом</p>${action('Все места')}<div class="k-row k-between"><span>Ранний заезд</span><button class="k-service-action" data-open-sheet="service">Добавить</button></div></div>`,
 'icon-button':()=>`<div class="k-row k-wrap"><button class="k-icon-button" aria-label="Назад">${icon('back')}</button><button class="k-icon-button k-icon-button--plain" aria-label="Уведомления, есть непрочитанные">${icon('bell')}<span class="k-unread"></span></button><button class="k-icon-button k-icon-button--plain k-save" aria-label="Сохранить отель" aria-pressed="false" data-save>${icon('heart')}</button><button class="k-icon-button" disabled aria-label="Поделиться">${icon('share')}</button></div>`,
 'field':()=>`<div class="k-stack">${field('Имя','Татьяна','autocomplete="given-name"')}${field('Телефон','','type="tel" placeholder="+7 999 000-00-00"')}<label class="k-field">Email<input class="k-input" type="email" value="tanya@" aria-invalid="true" aria-describedby="field-error"><span id="field-error" class="k-hint k-error">Проверьте адрес электронной почты</span></label>${field('Номер брони','KL-20418','readonly')}</div>`,
 'textarea':()=>`<label class="k-field"><span>Поделитесь впечатлениями</span><textarea class="k-input" maxlength="2000" placeholder="Что понравилось в поездке?"></textarea><span class="k-hint">Ваш отзыв поможет другим гостям выбрать отель</span></label>`,
 'select':()=>`<label class="k-field">Время заезда<span class="k-select"><select class="k-input"><option>14:00 · стандартный заезд</option><option>12:00 · ранний заезд</option><option>09:00 · ранний заезд</option></select>${icon('chevron')}</span></label>`,
 'checkbox':()=>`<div><label class="k-check"><input type="checkbox" checked>Завтрак включён</label><label class="k-check"><input type="checkbox">Бесплатная отмена</label><label class="k-check"><input type="checkbox" disabled>Нет доступных номеров</label></div>`,
 'radio':()=>`<fieldset style="border:0;padding:0;margin:0"><legend class="k-label">Тип ссылки</legend><label class="k-check"><input type="radio" name="share-type-example" value="read" checked>Только просмотр</label><label class="k-check"><input type="radio" name="share-type-example" value="manage">Управление поездкой</label></fieldset>`,
 'switch':()=>`<div><label class="k-switch">С питомцем<input type="checkbox" role="switch"></label><label class="k-switch">Командировка<input type="checkbox" role="switch" checked></label><label class="k-switch">На машине<input type="checkbox" role="switch"></label></div>`,
 'stepper':()=>`<div class="k-row k-between"><span class="k-label">Взрослые</span><div class="k-stepper" data-min="1" data-max="6"><button data-step="-1" aria-label="Уменьшить количество взрослых">−</button><output aria-live="polite">2</output><button data-step="1" aria-label="Увеличить количество взрослых">+</button></div></div>`,
 'tabs':()=>`<div class="k-stack">${tabs('demo-view')}${tabs('demo-sort',['Для вас','Дешевле','Рейтинг'])}${tabs('demo-line',['Активные','Выполненные'],'line')}</div>`,
 'chips':()=>`<div class="k-chips"><button class="k-chip" aria-label="Все фильтры" data-open-sheet="filters">${icon('sliders')}</button>${['Завтрак включён','Без предоплаты','Бесплатная отмена'].map(t=>`<button class="k-chip" aria-pressed="false" data-chip>${t}</button>`).join('')}</div>`,
 'calendar':()=>`<div class="k-stack"><p class="k-label">Сентябрь 2026</p><div class="k-calendar" data-calendar><span>Пн</span><span>Вт</span><span>Ср</span><span>Чт</span><span>Пт</span><span>Сб</span><span>Вс</span><span></span>${Array.from({length:30},(_,i)=>`<button aria-label="${i+1} сентября 2026" aria-pressed="${i===11||i===18}" ${i>11&&i<18?'class="k-in-range"':''}>${i+1}</button>`).join('')}</div><p class="k-caption k-muted" data-calendar-summary>12–19 сентября · 7 ночей</p></div>`,
 'uploader':()=>`<div class="k-stack">${upload('demo-upload')}</div>`,
 'rating':()=>`<div class="k-stack">${rating('demo-stars')}</div>`,
 'header':()=>`<header class="k-header"><span class="k-wordmark">ключи</span><button class="k-icon-button k-icon-button--plain" aria-label="Уведомления" data-open-sheet="notifications">${icon('bell')}<span class="k-unread"></span></button><button class="k-icon-button k-icon-button--plain" aria-label="Профиль" data-open-sheet="profile"><img class="k-avatar" src="assets/avatar.jpg" alt=""></button></header>`,
 'subheader':()=>`<header class="k-header k-subheader"><button class="k-icon-button" aria-label="Назад" data-toast="Возврат на исходный экран">${icon('back')}</button><h2 class="k-title">Бронь и документы</h2></header>`,
 'bottom-nav':()=>`<nav class="k-nav" aria-label="Основные разделы">${[['trips','Поездки'],['search','Найти'],['chat','Чаты'],['gift','Выгоды']].map(([ic,label],i)=>`<button ${i===0?'aria-current="page"':''} data-nav="${i}">${icon(ic)}<span>${label}</span></button>`).join('')}</nav>`,
 'card':()=>`<div class="k-stack"><div class="k-card"><h3 class="k-section">Депозит</h3><p class="k-muted">Белая поверхность и общая обводка</p></div><div class="k-card k-card--soft"><p class="k-label">Информационный акцент</p></div><div class="k-card k-card--positive"><p class="k-label">Баллы за рекомендацию</p></div></div>`,
 'data-rows':()=>`<div class="k-card">${rows([['Категория','Стандарт'],['Гости','2 взрослых'],['Завтрак','Включён'],['Wi-Fi','Включён']])}</div>`,
 'status':()=>`<div class="k-row k-wrap">${status('Бронь подтверждена','',true)}${status('Оплачено','',true)}${status('Оплачено частично','info')}${status('Запрошен','info')}${status('Одобрено','',true)}${status('В работе','warning')}${status('Выполнено','neutral')}${status('Не удалось','danger')}</div>`,
 'accordion':()=>`<div class="k-card">${['Как тратить баллы','Как копить баллы','Больше с каждой поездкой'].map((t,i)=>`<details class="k-accordion"><summary>${t}${icon('chevron')}</summary><div>${['Используйте доступные баллы при оплате новой брони. Сумма списания показана до подтверждения.','После завершения поездки начисления появятся в истории баллов.','Уровень и прогресс видны в карточке лояльности. Условия зависят от программы.'][i]}</div></details>`).join('')}</div>`,
 'booking-hero':()=>hero('before'),'stay-hero':()=>hero('stay'),'completed-hero':()=>hero('after'),
 'search-empty':()=>`<div class="k-stack"><img src="assets/next-trip.jpg" alt="Идея для следующего путешествия" style="height:180px;width:100%;border-radius:20px"><div><h3 class="k-display">Куда отправимся?</h3><p class="k-muted" style="margin-top:8px">Предстоящих поездок пока нет.<br>Ваш следующий отель уже ждёт.</p></div>${button('Найти отель','','data-toast="Открыть раздел Найти"')}</div>`,
 'service-row':()=>`<div class="k-card"><h3 class="k-section">Добавить к поездке</h3>${service('Ранний заезд','clock','Не включён · от 1 200 ₽')}${service('Завтрак','coffee','Добавлен за доплату · 680 ₽','Изменить','positive')}${action('Все услуги отеля')}</div>`,
 'service-detail':()=>`<div class="k-stack"><h3 class="k-title">Поздний выезд</h3><p class="k-muted">Выберите время. Отель подтвердит возможность позднего выезда.</p><label class="k-check"><input type="radio" name="late-time" checked>До 15:00 · 1 200 ₽</label><label class="k-check"><input type="radio" name="late-time">До 18:00 · 2 400 ₽</label>${button('Добавить услугу','','data-toast="Запрос отправлен. Возврат на предыдущий экран"')}</div>`,
 'orders':()=>`<div class="k-card"><details class="k-accordion"><summary><span><span class="k-section">Услуги и счёт</span><span class="k-caption k-muted" style="display:block">3 активные · ближайшая в 14:30</span></span>${icon('chevron')}</summary><div class="k-stack">${tabs('demo-orders',['Активные','Выполненные'])}<div class="k-stack k-stack--small"><div class="k-row k-between"><span>Еда в номер</span>${status('В работе','warning')}</div><p class="k-caption">Доставим сегодня в 14:30</p><div class="k-row k-between"><span>Уборка</span>${status('Одобрено','',true)}</div><p class="k-caption">Сегодня, 15:00–16:00</p></div></div></details><button class="k-link k-footer" data-open-sheet="bill"><span>Текущий счёт</span><span>480 ₽ ${icon('chevron',true)}</span></button></div>`,
 'bill':()=>`<div class="k-card k-stack"><div class="k-row k-between"><h3 class="k-section">Депозит</h3>${icon('card')}</div><p class="k-section">9 520 ₽</p><p class="k-caption k-muted">Остаток на счёте</p>${rows([['Внесено','10 000 ₽'],['Потрачено','480 ₽']])}${action('Детализация счёта')}</div>`,
 'breakfast':()=>`<div class="k-stack">${gallery(['breakfast.png','restaurant.webp','buffet.png'])}<div><h3 class="k-section">Завтрак · шведский стол</h3><p class="k-muted">Ресторан, 1 этаж · 07:00–11:00</p></div><div class="k-row k-between"><span>680 ₽ / гость</span>${status('Не включён','neutral')}</div>${button('Добавить услугу','','data-toast="Услуга добавлена. Возврат на предыдущий экран"')}</div>`,
 'wifi':()=>`<div class="k-card k-stack"><div class="k-row">${icon('wifi')}<h3 class="k-section">Wi-Fi</h3></div>${rows([['Сеть','Maidens Guest'],['Пароль','<span data-password>••••••••</span>']])}<div class="k-grid">${button('Показать','secondary','data-reveal')}${button('Скопировать','secondary','data-copy="Welcome2026"')}</div></div>`,
 'problem':()=>`<form class="k-stack" data-example-form><label class="k-field">Что случилось?<span class="k-select"><select class="k-input"><option>В номере</option><option>С услугой</option><option>Другое</option></select>${icon('chevron')}</span></label><label class="k-field">Опишите проблему<textarea class="k-input" required></textarea></label>${upload('problem')}${button('Отправить','','type="submit"')}</form>`,
 'gallery':()=>gallery(),'hotel-card':()=>hotel(),
 'hotel-details':()=>`<div class="k-stack">${gallery()}<div><p class="k-caption k-muted">Отель · ★★★★★</p><h3 class="k-title">Maidens Hotel</h3></div><p>Современный отель для спокойного отдыха и знакомства с городом.</p><div class="k-row k-wrap">${['Спа','Вкусные завтраки','У моря'].map(t=>`<span class="k-tag">${t}</span>`).join('')}</div><div class="k-row"><span class="k-score">9,4</span><span class="k-caption">128 отзывов</span></div>${button('Выбрать номер от 28 980 ₽','','data-open-sheet="rooms"')}</div>`,
 'room-card':()=>`<div class="k-card k-stack"><img class="k-room-photo" src="assets/hotel.jpg" alt="Пример интерьера номера"><div><h3 class="k-section">Стандарт</h3><p class="k-caption k-muted">24 м² · 2 гостя · двуспальная кровать</p></div>${rows([['Завтрак','Включён'],['Отмена','Бесплатно до 10 сентября']])}${button('Выбрать · 28 980 ₽','','data-toast="Тариф выбран"')}</div>`,
 'search-form':()=>`<div class="k-stack"><h3 class="k-display">Куда поедем?</h3>${tabs('demo-search',['Знаю что ищу','Нужен совет'])}<div class="k-card k-card--soft k-stack">${field('Город','Сочи')}<div class="k-grid">${field('Заезд','2026-10-01','type="date"')}${field('Выезд','2026-10-20','type="date"')}</div>${button('2 взрослых','secondary','data-open-sheet="guests"')}${button('Найти отель','','data-toast="Параметры поиска применены"')}</div></div>`,
 'history':()=>`<div class="k-history"><button data-toast="Открыть поиск: Сочи"><strong>Сочи</strong><span class="k-caption">1–20 окт · 2 взр.</span></button><button data-toast="Открыть поиск: Казань"><strong>Казань</strong><span class="k-caption">9–12 окт · 2 взр.</span></button></div>`,
 'photo-search':()=>`<div class="k-photo-promo"><div><h3 class="k-section">Подбор по фото</h3><p class="k-caption" style="margin:8px 0 12px;color:#dbe5ff">Покажите место,<br>о котором мечтаете</p>${button('Добавить фото','secondary','data-open-sheet="photos"')}</div><img src="assets/cafe.jpg" alt="Атмосферное кафе"></div>`,
 'collections':()=>`<div class="k-collections">${[['deals','Горячие скидки'],['weekend','На пару дней'],['anywhere','Куда угодно']].map(([f,t])=>`<button data-toast="Подборка: ${t}"><img src="assets/${f}.svg" alt="">${t}</button>`).join('')}</div>`,
 'nearby':()=>`<article class="k-card"><div class="k-row k-between"><h3 class="k-section">Рядом с вами</h3>${icon('pin')}</div><p class="k-muted" style="margin-top:8px">Места по вашим интересам</p><div class="k-nearby-art"><img src="assets/theatre.jpg" alt="Театр"><img src="assets/cafe.jpg" alt="Кафе"></div><div class="k-row k-between">${action('Места на карте')}${action('Все места')}</div></article>`,
 'map':()=>map(),
 'reviews':()=>`<div class="k-card k-stack"><div class="k-row k-between"><h3 class="k-section">Отзывы гостей</h3><span class="k-score">9,4</span></div><p class="k-caption k-muted">128 отзывов</p><p>«Красивый интерьер, внимательная команда и отличный завтрак. Вернёмся ещё!»</p><p class="k-caption k-muted">Анна · сентябрь 2026</p>${action('Все отзывы')}</div>`,
 'payment':()=>`<div class="k-stack"><div class="k-card">${rows([['Maidens Hotel','7 ночей'],['Стандарт','2 взрослых'],['Стоимость','44 800 ₽']])}</div><div class="k-card"><div class="k-row k-between"><h3 class="k-section">Данные гостей</h3>${icon('users')}</div><div class="k-list-row"><span class="k-grow">Татьяна Глазырина</span><button class="k-link" data-open-sheet="guest">Изменить</button></div><button class="k-link" data-open-sheet="guest">Добавить второго гостя</button></div><label class="k-switch">Использовать Баллы Ключей<input type="checkbox" role="switch"></label>${button('Оплатить 44 800 ₽','','data-open-sheet="payment"')}</div>`,
 'booking-documents':()=>`<div class="k-stack"><div class="k-card k-stack"><div class="k-row k-wrap k-between"><span class="k-label">№ KL-20418</span>${status('Бронь подтверждена','',true)}</div><h3 class="k-section">Maidens Hotel</h3>${rows([['Заезд','12 сентября, с 14:00'],['Выезд','19 сентября, до 12:00'],['Проживание','7 ночей'],['Номер','Стандарт'],['Гости','2 взрослых']])}<hr class="k-rule"><h3 class="k-section">Тариф и питание</h3>${rows([['Тариф','Гибкий'],['Завтрак','Включён'],['Wi-Fi','Включён']])}<hr class="k-rule"><div class="k-row k-between"><h3 class="k-section">Оплата</h3>${status('Оплачено','',true)}</div>${rows([['Стоимость','44 800 ₽'],['К оплате','0 ₽']])}</div>${button('Скачать документы','secondary','data-open-sheet="documents"')}</div>`,
 'document-picker':()=>`<div class="k-stack"><h3 class="k-title">Документы поездки</h3>${['Чек на проживание','Подтверждение брони'].map(t=>`<button class="k-list-row" data-download-example>${icon('doc')}<span class="k-grow">${t}<span class="k-caption k-muted" style="display:block">PDF</span></span>${icon('download')}</button>`).join('')}${button('Сохранить все документы','','data-download-example')}</div>`,
 'change-booking':()=>`<div class="k-stack"><h3 class="k-title">Новые условия</h3><button class="k-link" data-toast="Вернуться к выбору дат и гостей">${icon('back',true)}Назад к изменениям</button>${rows([['Даты','12–19 сентября'],['Гости','2 взрослых'],['Новая стоимость','44 800 ₽'],['Доплата','0 ₽']])}${button('Подтвердить изменения','','data-toast="Бронь успешно изменена"')}</div>`,
 'checkin':()=>`<div class="k-stack"><div class="k-row k-between"><h3 class="k-title">Онлайн-регистрация</h3><span class="k-caption k-muted">1 / 2</span></div>${field('Фамилия','Глазырина')}${field('Имя','Татьяна')}${field('Документ','','placeholder="Серия и номер паспорта"')}${button('Продолжить','','data-open-sheet="checkin"')}</div>`,
 'share':()=>`<div class="k-stack"><h3 class="k-title">Поделиться поездкой</h3><div class="k-row"><img src="assets/hotel.jpg" alt="" style="width:64px;height:64px;border-radius:14px"><div><span class="k-label">Maidens Hotel</span><p class="k-caption k-muted">12–19 сентября · 7 ночей</p></div></div><label class="k-check"><input type="radio" name="trip-share" value="read" checked><span>Только просмотр<span class="k-caption k-muted" style="display:block">Получатель сможет посмотреть поездку</span></span></label><label class="k-check"><input type="radio" name="trip-share" value="manage"><span>Управление поездкой<span class="k-caption k-muted" style="display:block">Можно добавить в приложение и изменить</span></span></label>${button('Поделиться ссылкой','','data-copy="https://example.com/trip/read-only-example"')}</div>`,
 'route':()=>`<div class="k-stack"><h3 class="k-title">Построить маршрут</h3><p class="k-muted">Выберите приложение</p>${button('Яндекс Карты','secondary','data-toast="Переход во внешнее приложение: Яндекс Карты"')}${button('Яндекс Go','secondary','data-open-sheet="taxi"')}</div>`,
 'loyalty':()=>`<div class="k-card k-card--brand k-stack"><div class="k-row k-between"><h3 class="k-section">Баллы Ключей</h3><span class="k-caption">Silver</span></div><p class="k-display">2 240</p><p class="k-caption k-muted">На следующую поездку</p><div><div class="k-loyalty-progress"><span></span></div><div class="k-row k-between k-caption"><span>Ваш прогресс</span><span>До Gold · 2 поездки</span></div></div></div>`,
 'referral':()=>referral(),
 'profile':()=>`<div class="k-stack"><div class="k-row"><button class="k-icon-button" style="width:64px;height:64px" aria-label="Изменить фото профиля" data-open-sheet="photos"><img class="k-avatar k-avatar--large" src="assets/avatar.jpg" alt=""></button><div><h3 class="k-title">Татьяна Глазырина</h3><p class="k-muted">+7 999 000-00-00</p></div></div><div class="k-card k-card--soft"><div class="k-row k-between"><span class="k-label">Silver · Ключи</span><span class="k-section">2 240 баллов</span></div></div><div class="k-card"><h3 class="k-section">Документы и оплата</h3>${[['doc','Паспорт'],['card','Способы оплаты']].map(([ic,t])=>`<button class="k-list-row" data-open-sheet="${ic==='doc'?'documents':'payment'}">${icon(ic)}<span class="k-grow">${t}</span>${icon('chevron')}</button>`).join('')}</div></div>`,
 'notifications':()=>`<div class="k-stack"><div class="k-row k-between"><h3 class="k-title">Уведомления</h3><button class="k-icon-button k-icon-button--plain" aria-label="Настроить уведомления" data-open-sheet="settings">${icon('sliders')}</button></div><button class="k-notice" data-unread="true" data-open-sheet="feedback">${icon('star')}<span class="k-grow"><span class="k-label">Как прошло проживание?</span><span class="k-caption k-muted" style="display:block">Поделитесь впечатлениями · сегодня</span></span></button><button class="k-notice" data-open-sheet="feedback">${icon('chat')}<span><span class="k-label">Как прошла первая ночь?</span><span class="k-caption k-muted" style="display:block">Позавчера</span></span></button><div class="k-notice">${icon('shield')}<span>Вход в приложение<span class="k-caption k-muted" style="display:block">12 сентября</span></span></div></div>`,
 'feedback':()=>`<div class="k-stack" data-feedback><div data-feedback-step="1" class="k-stack"><h3 class="k-title">Как прошло проживание?</h3><p class="k-muted">Оцените вашу поездку</p>${rating('flow-rating')}${button('Продолжить','','data-feedback-next disabled')}</div><div data-feedback-step="2" class="k-stack" hidden><button class="k-link" data-feedback-back>${icon('back',true)}Назад к оценке</button><h3 class="k-title">Поделитесь впечатлениями</h3><p class="k-muted">Ваш рассказ поможет другим гостям выбрать этот отель.</p><textarea class="k-input" aria-label="Ваши впечатления" placeholder="Что особенно понравилось?"></textarea>${upload('review')}${button('Отправить отзыв','','data-feedback-submit')}</div><div data-feedback-step="3" class="k-stack" hidden><h3 class="k-title">Спасибо за отзыв!</h3><p class="k-muted">Ваши впечатления помогут другим путешественникам.</p><div class="k-card k-card--positive k-stack" data-tips hidden><h3 class="k-section">Поблагодарить команду</h3><p>Если хотите, оставьте чаевые сотрудникам отеля.</p>${button('Оставить чаевые','secondary','data-toast="Открыть защищённую форму чаевых"')}</div></div></div>`,
 'chat':()=>`<div class="k-stack"><div class="k-chat-bubble">Добрый день, Татьяна! Будем рады помочь.<time>14:20</time></div><div class="k-chat-bubble k-chat-bubble--out">Можно заказать уборку к 15:00?<time>14:21</time></div><div class="k-chat-bubble">Да, передали команде. Подтвердим в услугах.<time>14:22</time></div><form class="k-chat-composer" data-chat-form><input class="k-input" aria-label="Сообщение" placeholder="Написать сообщение" required><button class="k-icon-button" aria-label="Отправить">${icon('arrow')}</button></form></div>`,
 'sheet':()=>`<div class="k-stack"><p class="k-muted">Панель открывается поверх текущего контекста. Escape закрывает её и возвращает фокус.</p>${button('Открыть нижнюю панель','secondary','data-open-sheet="filters"')}</div>`,
 'toast':()=>`<div class="k-stack">${button('Услуга добавлена','secondary','data-toast="Услуга добавлена"')}${button('Бронь изменена','secondary','data-toast="Бронь успешно изменена"')}</div>`,
 'empty-state':()=>`<div class="k-stack"><div class="k-empty">${icon('heart')}<h3 class="k-section">Сохранённых отелей пока нет</h3><p class="k-muted">Нажмите на сердечко у понравившегося отеля.</p></div><div class="k-card k-stack" aria-busy="true" aria-label="Загрузка"><div class="k-skeleton" style="height:80px"></div><div class="k-skeleton" style="width:70%"></div></div><div class="k-card"><p class="k-label">Не удалось загрузить данные</p><button class="k-link" data-toast="Повторяем загрузку">Попробовать снова</button></div></div>`
 };
 // Forms use real submit semantics, rather than a visual action masquerading as a submit.
 for(const key of Object.keys(demos)){const fn=demos[key];demos[key]=()=>fn().replace(/type="button"([^>]*?)type="submit"/g,'type="submit"$1');}
 window.KeyTemplates={icon,button,status,tabs,gallery,service,rows,hotel,hero,rating,upload,map,referral,demos,esc};
})();
